// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Ima5jvO_8VQW4JVVedH-iNE_pmqH4eQ',
    appId: '1:902083271661:android:1b89dc569b26d37c4ea5e4',
    messagingSenderId: '902083271661',
    projectId: 'tutorial-flutter-2-58917',
    storageBucket: 'tutorial-flutter-2-58917.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrC7zbs4hmEyuZBySgq6vWuDzJiM7RyUM',
    appId: '1:902083271661:ios:bdcda09c91fb60264ea5e4',
    messagingSenderId: '902083271661',
    projectId: 'tutorial-flutter-2-58917',
    storageBucket: 'tutorial-flutter-2-58917.appspot.com',
    iosClientId: '902083271661-dfh0s0c0jmfibgvfaf7dhf3647tmt8aj.apps.googleusercontent.com',
    iosBundleId: 'com.tutorialflutter2.tutorialFlutter2',
  );
}
